version: '3'
services:
  db:
    build:
        context: .
        dockerfile: ./Dockerfile
    container_name: "postgres_db"
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: wasm_db
      TZ: "Asia/Tokyo"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data